import type { Role } from '../types/role'

export const ROLES: Role[] = [
  {
    key: 'admin',
    label: 'System Admin',
    shortLabel: 'Admin',
    email: 'admin@qmics.io',
    demoName: 'Maya Chen',
    description: 'Configure the platform, manage users, define master data',
    accent: 'bg-ink-900 dark:bg-ink-50',
    glyph: 'shield',
  },
  {
    key: 'quality_manager',
    label: 'Quality Manager',
    shortLabel: 'Q. Manager',
    email: 'quality.manager@qmics.io',
    demoName: 'Rahul Iyer',
    description: 'Schedule inspections, review reports, approve quality records',
    accent: 'bg-accent-500',
    glyph: 'badge',
  },
  {
    key: 'safety_manager',
    label: 'Safety Manager',
    shortLabel: 'S. Manager',
    email: 'safety.manager@qmics.io',
    demoName: 'Anika Sharma',
    description: 'Oversee safety programs, verify corrective actions',
    accent: 'bg-signal-amber',
    glyph: 'badge',
  },
  {
    key: 'quality_inspector',
    label: 'Quality Inspector',
    shortLabel: 'Q. Inspector',
    email: 'quality.inspector@qmics.io',
    demoName: 'Priya Shah',
    description: 'Execute GMP and quality checks, capture evidence on the floor',
    accent: 'bg-accent-400',
    glyph: 'check',
  },
  {
    key: 'safety_inspector',
    label: 'Safety Inspector',
    shortLabel: 'S. Inspector',
    email: 'safety.inspector@qmics.io',
    demoName: 'Kabir Menon',
    description: 'Perform safety walkthroughs and HACCP verification',
    accent: 'bg-signal-amber',
    glyph: 'check',
  },
  {
    key: 'employee',
    label: 'Employee',
    shortLabel: 'Employee',
    email: 'employee@qmics.io',
    demoName: 'Diya Patel',
    description: 'Resolve assigned issues, upload evidence of corrective action',
    accent: 'bg-signal-green',
    glyph: 'user',
  },
  {
    key: 'top_management',
    label: 'Top Management',
    shortLabel: 'Executive',
    email: 'leadership@qmics.io',
    demoName: 'Vikram Bose',
    description: 'Monitor compliance, trends, and operational KPIs across sites',
    accent: 'bg-ink-700 dark:bg-ink-200',
    glyph: 'chart',
  },
]
